### ISSUE TITLE
Stuck in "preparing"

### ISSUE THREAD

**Issue by godofthunder8756** [daijro/shortlyai-scraper#1]
Likely due to the service catching on to all the bot accounts and changing their signing process.

**Comment by daijro** [comment]
Hello, this is an issue with torrequest starting a new tor instance (if it was an issue with the shortlyai scraper, it would be stuck on "Registering new account over TOR"). I will look into it. Thank you!

**Comment by Allamaris0** [comment]
It works for me. So thanks!

![obraz_2022-01-02_143914](https://user-images.githubusercontent.com/51059882/147877603-5d8da5de-f1d4-4e07-81ad-e038676fe815.png)

**Comment by daijro** [comment]
Hello, I narrowed down the issue to Tor not being called anymore for whatever reason. ~~You can temporarily fix this by adding the folder containing tor.exe to your PATH~~

Thank you for bringing my attention to this!

Edit: Hello! A fix has been released

**Comment by michaelmakr** [comment]
> Hello, I narrowed down the issue to Tor not being called anymore for whatever reason. ~You can temporarily fix this by adding the folder containing tor.exe to your PATH~
> 
> Thank you for bringing my attention to this!
> 
> Edit: Hello! A fix has been released

Thanks for the fix! It is a great reference for torrequests. Is support for commands like 'rewrite', 'shorten' and 'expand' possible with EssayGen?

**Comment by daijro** [comment]
> Thanks for the fix! It is a great reference for torrequests. Is support for commands like 'rewrite', 'shorten' and 'expand' possible with EssayGen?

Hello, yes it is absolutely possible! I didn't originally find it valuable enough to implement because of the strict character limits ShortlyAI includes

I'll be sure to look into it next time I get a break from class

**Comment by michaelmakr** [comment]
> Hello, yes it is absolutely possible! I didn't originally find it valuable enough to implement because of the strict character limits ShortlyAI includes
> 
> I'll be sure to look into it next time I get a break from class

Awesome!

**Comment by daijro** [comment]
@michaelmakr, ShortlyAI commands have now been implemented in [v1.3.0](https://github.com/daijro/EssayGen/releases). Thanks for the suggestion!

**Comment by michaelmakr** [comment]
> @michaelmakr, ShortlyAI commands have now been implemented in [v1.3.0](https://github.com/daijro/EssayGen/releases). Thanks for the suggestion!

Thank you for the update!
