### ISSUE TITLE
it no longer works

### ISSUE THREAD

**Issue by MeBeIris** [daijro/shortlyai-scraper#2]
it gives a error saying Tor couldn't be started

**Comment by daijro** [comment]
ShortlyAI has just added Cloudflare bot protection to their website. I don't know if it will be possible to work around it, but I will try this weekend to work on a patch.

**Comment by MeBeIris** [comment]
tyvm

**Comment by MeBeIris** [comment]
![image](https://user-images.githubusercontent.com/100975925/160219284-4978869c-08bb-4f84-97e8-d7f0c20ed39d.png)

**Comment by MeBeIris** [comment]
(thats error for reference)

**Comment by MeBeIris** [comment]
> ShortlyAI has just added Cloudflare bot protection to their website. I don't know if it will be possible to work around it, but I will try this weekend to work on a patch.

idk that much but doesn't it normally have to wait 5s?

**Comment by daijro** [comment]
Yes, if I do somehow get it working again, there will be a 5-10 second delay every 4 runs (this would asynchronous be in the background), and it would also have to be frequently updated to keep up with Cloudflare.

**Comment by MeBeIris** [comment]
> Yes, if I do somehow get it working again, there will be a 5-10 second delay every 4 runs (this would asynchronous be in the background), and it would also have to be frequently updated to keep up with Cloudflare.

ok thanks!

**Comment by MeBeIris** [comment]
what if you maybe used a diff API?

**Comment by MeBeIris** [comment]
also i found this https://github.com/VeNoMouS/cloudscraper

**Comment by daijro** [comment]
I came across that API earlier but I had no luck (the cloudflare v1 scraper is deprecated, and even then I would still have no way to solve the captcha). I'll try adding a QWebBrowser or use Selenium to open the link combined with an injected [Hcaptcha solver](https://greasyfork.org/en/scripts/425854-hcaptcha-solver-automatically-solves-hcaptcha-in-browser), but I have no experience using those so it may take a while before a fix is released.

Edit: Release has been posted. I have also added a new [no-tor](https://github.com/daijro/EssayGen/tree/no-tor) branch for those who do not want to run TOR (runs faster, less captchas).

**Comment by MeBeIris** [comment]
> I came across that API earlier but I had no luck (the cloudflare v1 scraper is deprecated, and even then I would still have no way to solve the captcha). I'll try adding a QWebBrowser or use Selenium to open the link combined with an injected [Hcaptcha solver](https://greasyfork.org/en/scripts/425854-hcaptcha-solver-automatically-solves-hcaptcha-in-browser), but I have no experience using those so it may take a while before a fix is released.

thanks for at least trying!
